package com.contagion.person;

import java.util.Arrays;
import java.util.List;

public class DataGenerator {
    private List<String> lastNames = Arrays.asList(
            "Nowak",
            "Kowalski",
            "Wiśniewski",
            "Dąbrowski",
            "Lewandowski",
            "Wójcik",
            "Kamiński",
            "Kowalczyk",
            "Zieliński",
            "Szymański",
            "Woźniak",
            "Kozłowski",
            "Jankowski",
            "Wojciechowski",
            "Kwiatkowski",
            "Kaczmarek",
            "Mazur",
            "Krawczyk",
            "Piotrowski",
            "Grabowski",
            "Nowakowski",
            "Pawłowski",
            "Michalski",
            "Nowicki",
            "Adamczyk",
            "Dudek",
            "Zając",
            "Wieczorek",
            "Jabłoński",
            "Król",
            "Majewski",
            "Olszewski",
            "Jaworski",
            "Wróbel",
            "Malinowski",
            "Pawlak",
            "Witkowski",
            "Walczak",
            "Stępień",
            "Górski",
            "Rutkowski",
            "Michalak",
            "Sikora",
            "Ostrowski",
            "Baran",
            "Duda"
    );
    private List<String> surnames = Arrays.asList(
            "Luca",
            "Marcus",
            "Marko",
            "Maxym",
            "Medard",
            "Mohamed",
            "Oktawiusz",
            "Paskal",
            "Robin",
            "Sajmon",
            "Valentino",
            "DB",
            "Debora",
            "Elif",
            "Emilie",
            "Erika",
            "Iwa",
            "Kira",
            "Latika",
            "Latoya",
            "Leokadia",
            "Leonia",
            "Ligia",
            "Lorena",
            "Luna",
            "Marieta"
    );
    private List<String> companyNames = Arrays.asList(
            "Microsoft",
            "Google",
            "Apple",
            "Intel",
            "Orlen",
            "PKO BP",
            "BZWBK"
    );

}
